### ISSUE TITLE
Bloom Into you Chapter 41 cannot be downloaded

### ISSUE THREAD

**Issue by Arany** [vignedev/dynasty-dl#1]
https://dynasty-scans.com/series/bloom_into_you

Chapter 41 lists as "undefined" and trying to download it raises an error (it tries to download from /undefined).

On the page itself, there is an empty ``<dt>`` tag right before it which might cause problems?

**Comment by vignedev** [comment]
The `<dt>` tag didn't directly cause the error, because it's reading the JSON of the chapter, which for some reason had a header set to null. That caused it being detected as a chapter with no permalink to it, thus the /undefined.json. 

Fixed in [last commit](https://github.com/vignedev/dynasty-dl/commit/d170973190640554b518d99b58d9aa825e95e750).

**Comment by Arany** [comment]
@vignedev Thanks for the fix!

It still shows as "undefined" when doing "--listChapters", even though it does show the chapter name during download

**Comment by vignedev** [comment]
Thanks for the heads up. Again, fixed in the [last commit](https://github.com/vignedev/dynasty-dl/commit/fa9eb58f349bd821cf24de0783c8a353047a9b62).

**Comment by vignedev** [comment]
I forgot to close this.
